### ISSUE TITLE
Total RP 3 tooltip line

### ISSUE THREAD

**Issue by Solanya** [Nasias/GBRadio3#3]
Hi, Total RP 3 dev here.

I've been informed of an issue with our tooltips involving your addon, regarding this modification:

https://github.com/Nasias/GBRadio3/blob/master/GBRadio/GBRadio.lua#L108

The globals should not be modified, they're meant to be read and used in more places than the tooltip.

The clean way to add version tooltip lines is to send the version over comms and hook the tooltip OnShow function. An example of that would be Musician:

https://github.com/LenweSaralonde/Musician/blob/master/modules/totalRP3/totalRP3.lua#L24
https://github.com/LenweSaralonde/Musician/blob/master/modules/totalRP3/totalRP3.lua#L50
https://github.com/LenweSaralonde/Musician/blob/master/core/Musician.Registry.lua#L344

**Comment by Nasias** [comment]
Hi Solanya, thanks for reaching out and for your feedback, apologies for not responding until now. I appreciate the advice on this. I'm strapped for time at the moment so I've just removed the dirty hook logic in this version for now to stop it causing any issues with TRP3, and will look to implement your clean proposal for the next version after this.

Cheers.
