### ISSUE TITLE
Disable colorization of GBRRadio note on TRP3 Tooltip

### ISSUE THREAD

**Issue by DJScias** [Nasias/GBRadio3#4]
Hello there,

I noticed someone walking around today that had GBRRadio enabled without me having it on. Their tooltip was the following:
![image](https://user-images.githubusercontent.com/439655/193429381-d1db4310-a0c6-4207-a5c4-3ecc4904f3c5.png)

While it being enabled by default, even if the addon is mutually enabled, is related to #3 so another issue entirely.

However, I was curious if it's possible to not colorize it by default, or add an option? Considering it is adding unnecessary colorization which we can't even disable/change ourselves. As is obvious from the tooltip displayed above, sort of destroying the simplistic vibe it had before.

Thanks in advance.

**Comment by DJScias** [comment]
Found another addition that's even bigger and flashier on a different profile.

I should once more reaffirm that no addon should honestly have one-sided power to make a TRP look like a traffic light filled with a plethora of extra colors. Up until now colorization is tightly controlled by the user (their name through class color) or the client set by the user itself (https://github.com/Total-RP/Total-RP-3/pull/607).

This current colorization is forced to users not using the addon (as per #3) but even if that is resolved it should still not have the power to colorize tooltips without giving the end user the means to disable or mute it. Considering it is not related to the user either (who defines their own color in a class) and thus nobody's choice.
![unknown-70](https://user-images.githubusercontent.com/439655/193450460-3b4b9fc8-b2d8-4c75-9b82-acc1ad9954bb.png)

**Comment by Nasias** [comment]
Hey @DJScias,

Thanks for your feedback around this and apologies for the delay in getting back to you. This feature has currently been removed in the current version, due to feedback from the TRP3 team around how this version display has been implemented and was causing problems.

I appreciate you concern around the colourisation and I agree with what you've said. When this is re-implemented in the future, it will use the same font colour as the standard TRP3 version text in line with your proposal.

Cheers.

**Comment by DJScias** [comment]
> Hey @DJScias,
> 
> Thanks for your feedback around this and apologies for the delay in getting back to you. This feature has currently been removed in the current version, due to feedback from the TRP3 team around how this version display has been implemented and was causing problems.
> 
> I appreciate you concern around the colourisation and I agree with what you've said. When this is re-implemented in the future, it will use the same font colour as the standard TRP3 version text in line with your proposal.
> 
> Cheers.

Hey hey,

No worries. Honestly the issue isn't the colorization in and by itself. But it was mostly that it's probably better off as a toggle option or a client-side option.

That way everyone's happy of course, but thank you for addressing it nonetheless. :)
